//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_library {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("School_library.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string ActiveCheckboxText {
            get {
                return ResourceManager.GetString("ActiveCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        public static string AddLoanWindow_book {
            get {
                return ResourceManager.GetString("AddLoanWindow_book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string AddLoanWindow_copy {
            get {
                return ResourceManager.GetString("AddLoanWindow_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string AddLoanWindow_Error {
            get {
                return ResourceManager.GetString("AddLoanWindow_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured while adding a loan.
        /// </summary>
        public static string AddLoanWindow_ErrorWhileAdding {
            get {
                return ResourceManager.GetString("AddLoanWindow_ErrorWhileAdding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loan has been added.
        /// </summary>
        public static string AddLoanWindow_LoanAdded {
            get {
                return ResourceManager.GetString("AddLoanWindow_LoanAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string AddLoanWindow_LoanSuccess {
            get {
                return ResourceManager.GetString("AddLoanWindow_LoanSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        public static string AddLoanWindow_member {
            get {
                return ResourceManager.GetString("AddLoanWindow_member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a copy.
        /// </summary>
        public static string AddLoanWindow_mustSelectCopy {
            get {
                return ResourceManager.GetString("AddLoanWindow_mustSelectCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a member.
        /// </summary>
        public static string AddLoanWindow_mustSelectMember {
            get {
                return ResourceManager.GetString("AddLoanWindow_mustSelectMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected member is inactive.
        /// </summary>
        public static string AddLoanWindow_userInactiveMessage {
            get {
                return ResourceManager.GetString("AddLoanWindow_userInactiveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new book.
        /// </summary>
        public static string AddNewBookButton {
            get {
                return ResourceManager.GetString("AddNewBookButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new copy.
        /// </summary>
        public static string AddNewCopy {
            get {
                return ResourceManager.GetString("AddNewCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new member.
        /// </summary>
        public static string AddNewMemberText {
            get {
                return ResourceManager.GetString("AddNewMemberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must fill all the fields and choose a user type..
        /// </summary>
        public static string AddUserFormRequirementsMessage {
            get {
                return ResourceManager.GetString("AddUserFormRequirementsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application initialization has failed.Couldn&apos;t find config file..
        /// </summary>
        public static string AppInitFailed {
            get {
                return ResourceManager.GetString("AppInitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author: .
        /// </summary>
        public static string AuthorTextBlock {
            get {
                return ResourceManager.GetString("AuthorTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available: .
        /// </summary>
        public static string AvailableText {
            get {
                return ResourceManager.GetString("AvailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The book has been added..
        /// </summary>
        public static string BookAdded {
            get {
                return ResourceManager.GetString("BookAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Books.
        /// </summary>
        public static string BooksTabName {
            get {
                return ResourceManager.GetString("BooksTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear filters.
        /// </summary>
        public static string ClearFiltersButton {
            get {
                return ResourceManager.GetString("ClearFiltersButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition: .
        /// </summary>
        public static string ConditionText {
            get {
                return ResourceManager.GetString("ConditionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy added..
        /// </summary>
        public static string CopyAddedMessage {
            get {
                return ResourceManager.GetString("CopyAddedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t access the database.
        /// </summary>
        public static string CouldntAccessDatabase {
            get {
                return ResourceManager.GetString("CouldntAccessDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t add copy..
        /// </summary>
        public static string CouldntAddCopy {
            get {
                return ResourceManager.GetString("CouldntAddCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t add new author!.
        /// </summary>
        public static string CouldntAddNewAuthor {
            get {
                return ResourceManager.GetString("CouldntAddNewAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t add the book!.
        /// </summary>
        public static string CouldntAddNewBook {
            get {
                return ResourceManager.GetString("CouldntAddNewBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t add new genre!.
        /// </summary>
        public static string couldntAddNewGenre {
            get {
                return ResourceManager.GetString("couldntAddNewGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme.
        /// </summary>
        public static string DarkThemeText {
            get {
                return ResourceManager.GetString("DarkThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inputs must not be empty!.
        /// </summary>
        public static string DataInputsEmpty {
            get {
                return ResourceManager.GetString("DataInputsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected copy.
        /// </summary>
        public static string DeleteSelectedCopy {
            get {
                return ResourceManager.GetString("DeleteSelectedCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery date: .
        /// </summary>
        public static string DeliveryDateText {
            get {
                return ResourceManager.GetString("DeliveryDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit book info.
        /// </summary>
        public static string EditBookWindowName {
            get {
                return ResourceManager.GetString("EditBookWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition: .
        /// </summary>
        public static string EditionTextblock {
            get {
                return ResourceManager.GetString("EditionTextblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre name: .
        /// </summary>
        public static string GenreNameTextblock {
            get {
                return ResourceManager.GetString("GenreNameTextblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre: .
        /// </summary>
        public static string GenreTextBlock {
            get {
                return ResourceManager.GetString("GenreTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given password is incorrect!.
        /// </summary>
        public static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light theme.
        /// </summary>
        public static string LightThemeText {
            get {
                return ResourceManager.GetString("LightThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add loan.
        /// </summary>
        public static string Loans_AddLoanButton {
            get {
                return ResourceManager.GetString("Loans_AddLoanButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string Loans_BooksTextBlock {
            get {
                return ResourceManager.GetString("Loans_BooksTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book title.
        /// </summary>
        public static string Loans_BookTitle {
            get {
                return ResourceManager.GetString("Loans_BookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrowed at date: .
        /// </summary>
        public static string Loans_BorrowedAtDate {
            get {
                return ResourceManager.GetString("Loans_BorrowedAtDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrowed from: .
        /// </summary>
        public static string Loans_BorrowedFrom {
            get {
                return ResourceManager.GetString("Loans_BorrowedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy ID.
        /// </summary>
        public static string Loans_CopyID {
            get {
                return ResourceManager.GetString("Loans_CopyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string Loans_FirstName {
            get {
                return ResourceManager.GetString("Loans_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Loans_LastName {
            get {
                return ResourceManager.GetString("Loans_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book title: .
        /// </summary>
        public static string Loans_listbox_bookTitle {
            get {
                return ResourceManager.GetString("Loans_listbox_bookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy ID: .
        /// </summary>
        public static string Loans_listbox_copyID {
            get {
                return ResourceManager.GetString("Loans_listbox_copyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name: .
        /// </summary>
        public static string Loans_listbox_firstName {
            get {
                return ResourceManager.GetString("Loans_listbox_firstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name: .
        /// </summary>
        public static string Loans_listbox_lastName {
            get {
                return ResourceManager.GetString("Loans_listbox_lastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned at date: .
        /// </summary>
        public static string Loans_listbox_returnedAt {
            get {
                return ResourceManager.GetString("Loans_listbox_returnedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID: .
        /// </summary>
        public static string Loans_listbox_userID {
            get {
                return ResourceManager.GetString("Loans_listbox_userID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string Loans_MembersTextBlock {
            get {
                return ResourceManager.GetString("Loans_MembersTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only returned.
        /// </summary>
        public static string Loans_OnlyReturned {
            get {
                return ResourceManager.GetString("Loans_OnlyReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned at date:.
        /// </summary>
        public static string Loans_ReturnDate {
            get {
                return ResourceManager.GetString("Loans_ReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned to:.
        /// </summary>
        public static string Loans_ReturnedTo {
            get {
                return ResourceManager.GetString("Loans_ReturnedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return loan.
        /// </summary>
        public static string Loans_returnLoan {
            get {
                return ResourceManager.GetString("Loans_returnLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string Loans_UserID {
            get {
                return ResourceManager.GetString("Loans_UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Loans.
        /// </summary>
        public static string LoansTabName {
            get {
                return ResourceManager.GetString("LoansTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Members.
        /// </summary>
        public static string MembersTabName {
            get {
                return ResourceManager.GetString("MembersTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields for the new author must be filled out.
        /// </summary>
        public static string NewAuthorEmptyInputs {
            get {
                return ResourceManager.GetString("NewAuthorEmptyInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New author.
        /// </summary>
        public static string NewAuthorExpander {
            get {
                return ResourceManager.GetString("NewAuthorExpander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields for the new genre must be filled out!.
        /// </summary>
        public static string NewGenreEmptyInputs {
            get {
                return ResourceManager.GetString("NewGenreEmptyInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New genre.
        /// </summary>
        public static string NewGenreExpander {
            get {
                return ResourceManager.GetString("NewGenreExpander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New publisher.
        /// </summary>
        public static string NewPublisherExpander {
            get {
                return ResourceManager.GetString("NewPublisherExpander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields for the new publisher must be filled out!.
        /// </summary>
        public static string NewPublisherFieldsEmpty {
            get {
                return ResourceManager.GetString("NewPublisherFieldsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t add new publisher!.
        /// </summary>
        public static string NewPublisherNotAdded {
            get {
                return ResourceManager.GetString("NewPublisherNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition not specified.
        /// </summary>
        public static string NoConditionSpecified {
            get {
                return ResourceManager.GetString("NoConditionSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of copies: .
        /// </summary>
        public static string NumberOfCopiesTextBlock {
            get {
                return ResourceManager.GetString("NumberOfCopiesTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only active members.
        /// </summary>
        public static string OnlyActiveMembers {
            get {
                return ResourceManager.GetString("OnlyActiveMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only with available copies.
        /// </summary>
        public static string OnlyWithAvailableCopiesText {
            get {
                return ResourceManager.GetString("OnlyWithAvailableCopiesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password: .
        /// </summary>
        public static string PasswordText {
            get {
                return ResourceManager.GetString("PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher name: .
        /// </summary>
        public static string PublisherNameTextblock {
            get {
                return ResourceManager.GetString("PublisherNameTextblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher: .
        /// </summary>
        public static string PublisherTextBlock {
            get {
                return ResourceManager.GetString("PublisherTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A condition must be selected!.
        /// </summary>
        public static string SelectConditionMessage {
            get {
                return ResourceManager.GetString("SelectConditionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a date.
        /// </summary>
        public static string SelectDate {
            get {
                return ResourceManager.GetString("SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date must be selected!.
        /// </summary>
        public static string SelectDateMessage {
            get {
                return ResourceManager.GetString("SelectDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string SettingsTabName {
            get {
                return ResourceManager.GetString("SettingsTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to show/hide filters....
        /// </summary>
        public static string ShowHideFilters {
            get {
                return ResourceManager.GetString("ShowHideFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        public static string ThemesText {
            get {
                return ResourceManager.GetString("ThemesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been added..
        /// </summary>
        public static string UserAddedMessage {
            get {
                return ResourceManager.GetString("UserAddedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given username doesn&apos;t exist!.
        /// </summary>
        public static string UsernameDoesntExist {
            get {
                return ResourceManager.GetString("UsernameDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username: .
        /// </summary>
        public static string UsernameText {
            get {
                return ResourceManager.GetString("UsernameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured while adding a user..
        /// </summary>
        public static string UserNotAddedError {
            get {
                return ResourceManager.GetString("UserNotAddedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User type: .
        /// </summary>
        public static string UserTypeText {
            get {
                return ResourceManager.GetString("UserTypeText", resourceCulture);
            }
        }
    }
}
